/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Control;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author unifpschneider
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        c = new Control(this);
    }

    public JTextField getTXT_1() {
        return TXT_1;
    }

    public void setTXT_1(JTextField TXT_1) {
        this.TXT_1 = TXT_1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT_1 = new javax.swing.JTextField();
        BTT_0 = new javax.swing.JButton();
        BTT_1 = new javax.swing.JButton();
        BTT_2 = new javax.swing.JButton();
        BTT_3 = new javax.swing.JButton();
        BTT_4 = new javax.swing.JButton();
        BTT_5 = new javax.swing.JButton();
        BTT_6 = new javax.swing.JButton();
        BTT_7 = new javax.swing.JButton();
        BTT_8 = new javax.swing.JButton();
        BTT_9 = new javax.swing.JButton();
        BTT_div = new javax.swing.JButton();
        BTT_clear = new javax.swing.JButton();
        BTT_mult = new javax.swing.JButton();
        BTT_sub = new javax.swing.JButton();
        BTT_equal = new javax.swing.JButton();
        BTT_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        TXT_1.setEditable(false);
        TXT_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXT_1.setToolTipText("");
        TXT_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_1ActionPerformed(evt);
            }
        });

        BTT_0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_0.setText("0");
        BTT_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_0ActionPerformed(evt);
            }
        });

        BTT_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_1.setText("1");
        BTT_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_1ActionPerformed(evt);
            }
        });

        BTT_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_2.setText("2");
        BTT_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_2ActionPerformed(evt);
            }
        });

        BTT_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_3.setText("3");
        BTT_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_3ActionPerformed(evt);
            }
        });

        BTT_4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_4.setText("4");
        BTT_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_4ActionPerformed(evt);
            }
        });

        BTT_5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_5.setText("5");
        BTT_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_5ActionPerformed(evt);
            }
        });

        BTT_6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_6.setText("6");
        BTT_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_6ActionPerformed(evt);
            }
        });

        BTT_7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_7.setText("7");
        BTT_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_7ActionPerformed(evt);
            }
        });

        BTT_8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_8.setText("8");
        BTT_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_8ActionPerformed(evt);
            }
        });

        BTT_9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_9.setText("9");
        BTT_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_9ActionPerformed(evt);
            }
        });

        BTT_div.setBackground(new java.awt.Color(204, 204, 204));
        BTT_div.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_div.setText("/");
        BTT_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_divActionPerformed(evt);
            }
        });

        BTT_clear.setBackground(new java.awt.Color(204, 204, 204));
        BTT_clear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_clear.setText("C");
        BTT_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_clearActionPerformed(evt);
            }
        });

        BTT_mult.setBackground(new java.awt.Color(204, 204, 204));
        BTT_mult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_mult.setText("X");
        BTT_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_multActionPerformed(evt);
            }
        });

        BTT_sub.setBackground(new java.awt.Color(204, 204, 204));
        BTT_sub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_sub.setText("-");
        BTT_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_subActionPerformed(evt);
            }
        });

        BTT_equal.setBackground(new java.awt.Color(102, 102, 102));
        BTT_equal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_equal.setForeground(new java.awt.Color(255, 255, 255));
        BTT_equal.setText("=");
        BTT_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_equalActionPerformed(evt);
            }
        });

        BTT_add.setBackground(new java.awt.Color(204, 204, 204));
        BTT_add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTT_add.setText("+");
        BTT_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXT_1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTT_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(BTT_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTT_0, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(BTT_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTT_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_equal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTT_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(BTT_sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_mult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTT_div, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXT_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_div, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_1ActionPerformed

    private void BTT_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_8ActionPerformed
        String texto = TXT_1.getText();
        texto += "8";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_8ActionPerformed

    private void BTT_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_1ActionPerformed
        String texto = TXT_1.getText();
        texto += "1";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_1ActionPerformed

    private void BTT_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_2ActionPerformed
        String texto = TXT_1.getText();
        texto += "2";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_2ActionPerformed

    private void BTT_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_3ActionPerformed
        String texto = TXT_1.getText();
        texto += "3";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_3ActionPerformed

    private void BTT_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_4ActionPerformed
        String texto = TXT_1.getText();
        texto += "4";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_4ActionPerformed

    private void BTT_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_5ActionPerformed
        String texto = TXT_1.getText();
        texto += "5";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_5ActionPerformed

    private void BTT_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_6ActionPerformed
        String texto = TXT_1.getText();
        texto += "6";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_6ActionPerformed

    private void BTT_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_7ActionPerformed
        String texto = TXT_1.getText();
        texto += "7";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_7ActionPerformed

    private void BTT_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_9ActionPerformed
        String texto = TXT_1.getText();
        texto += "9";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_9ActionPerformed

    private void BTT_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_clearActionPerformed
        c.controlLimpa();
    }//GEN-LAST:event_BTT_clearActionPerformed

    private void BTT_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_0ActionPerformed
        String texto = TXT_1.getText();
        texto += "0";
        TXT_1.setText(texto);
    }//GEN-LAST:event_BTT_0ActionPerformed

    private void BTT_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_addActionPerformed
        c.controlSomar();
    }//GEN-LAST:event_BTT_addActionPerformed

    private void BTT_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_equalActionPerformed
        c.controlIgual();
    }//GEN-LAST:event_BTT_equalActionPerformed

    private void BTT_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_subActionPerformed
        c.controlSubtrair();
    }//GEN-LAST:event_BTT_subActionPerformed

    private void BTT_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_multActionPerformed
        c.controlMultiplicacao();
    }//GEN-LAST:event_BTT_multActionPerformed

    private void BTT_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_divActionPerformed
        c.controlDivisao();
    }//GEN-LAST:event_BTT_divActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }

    private Control c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTT_0;
    private javax.swing.JButton BTT_1;
    private javax.swing.JButton BTT_2;
    private javax.swing.JButton BTT_3;
    private javax.swing.JButton BTT_4;
    private javax.swing.JButton BTT_5;
    private javax.swing.JButton BTT_6;
    private javax.swing.JButton BTT_7;
    private javax.swing.JButton BTT_8;
    private javax.swing.JButton BTT_9;
    private javax.swing.JButton BTT_add;
    private javax.swing.JButton BTT_clear;
    private javax.swing.JButton BTT_div;
    private javax.swing.JButton BTT_equal;
    private javax.swing.JButton BTT_mult;
    private javax.swing.JButton BTT_sub;
    private javax.swing.JTextField TXT_1;
    // End of variables declaration//GEN-END:variables
}
