# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taskmanager.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'taskmanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11taskmanager.proto\x12\x0ctaskmanager\"\x1e\n\x0b\x43onnRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tConnReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"3\n\rCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bListRequest\"1\n\x0cListResponse\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.taskmanager.Task\"O\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf9\x02\n\x0bTaskManager\x12\x39\n\x06\x43reate\x12\x1b.taskmanager.CreateRequest\x1a\x12.taskmanager.Task\x12\x33\n\x03Get\x12\x18.taskmanager.GetRequest\x1a\x12.taskmanager.Task\x12=\n\x04List\x12\x19.taskmanager.ListRequest\x1a\x1a.taskmanager.ListResponse\x12\x39\n\x06Update\x12\x1b.taskmanager.UpdateRequest\x1a\x12.taskmanager.Task\x12:\n\x06\x44\x65lete\x12\x1b.taskmanager.DeleteRequest\x1a\x13.taskmanager.Empty\x12\x44\n\x0e\x43onnectionTest\x12\x19.taskmanager.ConnRequest\x1a\x17.taskmanager.ConnReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskmanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNREQUEST']._serialized_start=35
  _globals['_CONNREQUEST']._serialized_end=65
  _globals['_CONNREPLY']._serialized_start=67
  _globals['_CONNREPLY']._serialized_end=95
  _globals['_TASK']._serialized_start=97
  _globals['_TASK']._serialized_end=167
  _globals['_CREATEREQUEST']._serialized_start=169
  _globals['_CREATEREQUEST']._serialized_end=220
  _globals['_GETREQUEST']._serialized_start=222
  _globals['_GETREQUEST']._serialized_end=246
  _globals['_LISTREQUEST']._serialized_start=248
  _globals['_LISTREQUEST']._serialized_end=261
  _globals['_LISTRESPONSE']._serialized_start=263
  _globals['_LISTRESPONSE']._serialized_end=312
  _globals['_UPDATEREQUEST']._serialized_start=314
  _globals['_UPDATEREQUEST']._serialized_end=393
  _globals['_DELETEREQUEST']._serialized_start=395
  _globals['_DELETEREQUEST']._serialized_end=422
  _globals['_EMPTY']._serialized_start=424
  _globals['_EMPTY']._serialized_end=431
  _globals['_TASKMANAGER']._serialized_start=434
  _globals['_TASKMANAGER']._serialized_end=811
# @@protoc_insertion_point(module_scope)
